#!/bin/bash

EXEC=./fsi
OUTFILE=Refine2D.out

# List of MPI process counts
PROCS=(1 2 4 6 8 10 12 14 16 32)

echo "Scaling run started at $(date)" >> "$OUTFILE"
echo "--------------------------------" >> "$OUTFILE"

for n in "${PROCS[@]}"; do
    echo "" >> "$OUTFILE"
    echo "Running with $n process(es)" >> "$OUTFILE"
    echo "----------------------------" >> "$OUTFILE"

    if [ "$n" -eq 1 ]; then
        /usr/bin/time -p "$EXEC" >> "$OUTFILE" 2>&1
    else
        /usr/bin/time -p mpirun -n "$n" "$EXEC" >> "$OUTFILE" 2>&1
    fi
done

echo "" >> "$OUTFILE"
echo "--------------------------------" >> "$OUTFILE"
echo "Config.prm parameters:" >> "$OUTFILE"
echo "--------------------------------" >> "$OUTFILE"

cat ../config.prm >> "$OUTFILE"


echo "" >> "$OUTFILE"
echo "Scaling run finished at $(date)" >> "$OUTFILE"
